import 'package:untitled/screens/description_page.dart';
class Desc{
  String name='',desc='';
  String getData(String name){
    switch(name)
    { case "TAJ MAHAL": return "The World Wonder of India, the marble mausoleum is the heart of tourism of India. Agra is not just about Taj Mahal. Agra is the remainder of Mughal dynasty, for today’s Agra sightseeing tour.\n \nFilled with numerous unique structures of Mughal region, this destination attracts millions of people, every year. Do not forget to shop while you are in Agra. The best way to scale Agra is by taking the Golden Triangle Tour.\n \nOctober to March is the best time to visit Agra.";
      case "RANN OF KUTCH": return "This is the salt desert of the country. Rann of Kutch is famous for its unique landscape. Camel safari, camping and other activities are famous in this region. However, it is best visited during the Rann Utsav. If you are looking for interesting destinations, Rann of Kutch is a top destination and best places to visit in India in the map.\n \nBest time to visit Rann of Kutch are Winters. From October to February the weather is pleasant and perfect time for sightseeing. ";
      case "VARANASI": return "Ganga Arti is not the entire itinerary of Varanasi. It is one of the oldest inhabited areas in the world, which is still populated. Varanasi holds numerous alleys, filled with temples. The either side of River Ganges is filled with 88 different ghats, each famous for different elements. Varanasi is also the gateway to reach Sarnath, the pinnacle of Buddhism pilgrimage in India.\n \n Winters is the best time to explore the beauty of Varanasi. From November to March the weather of Varanasi is pleasant during day time so that you can easily explore the city.";
      case "ANDAMAN ISLANDS": return "Although assumed as single destination, this place is a cluster of small islands, each famous for beaches and unique water activities. Starting from simple boating to scuba diving, you can enjoy all kinds of water activities here. On the silky beaches, the place provides endless entertainment and beautiful culture.\n \nAndaman is not the only island of India but this is the one of the famous places to visit in India. There are numerous other famous islands and some unique and daring islands. Are you up for some adrenaline time?\n \nFrom October to May is the ideal time to visit Andaman Islands.";
      case "COORG": return "India has a long list of hill stations of varying themes and styles. Of all, Coorg is one important destination for mountainous beauty. Famous for its simplicity in attractions and high level of intoxicating activities, this hill station is also called as the Scotland of East. The plantations, unique viewpoints and fresh flora of the region would rejuvenate you.\n \n You can visit Coorg throughout the year. From October to April is the ideal time to visit Coorg.";
      case "VALLEY OF FLOWERS": return "A botanical garden can cheer you up, no matter what. So, how about a valley filled with acres and acres of flowers of varying hue? Visit the Valley of Flowers of Uttarkhand, during early monsoon. The land is filled with wild flowers of pink, green, blue, orange and so on. It is rainbow on the grass. You need trek for a few hours to watch this lively beauty of nature.\n \nFrom June to October is the best time to visit Valley of Flower.";
      case "KANYA KUMARI": return "The southern tip of the country is flourished with culture and nature. Called as the Cape Comorin in the past, this region is lined with trees, small hillocks, rugged valleys and most importantly, the tri-colored sea. This is the best place to spot sunset and sunrise in India. People sail into the ocean to spot Vivekanada Rock and Thiruvalluvar statue. Apart from these, you can find numerous temples in and around the city.";
      case "LAKSHADWEEP": return "The white sandy coastlines, abundant scenic charm and tranquil surroundings make Lakshadweep a popular family as well as honeymooning destination. It is visited by tourists from all around the globe. The best time to visit Lakshadweep is between the months of September and May, when the weather is pleasant and conducive for water sports activities. The temperature remains between 22°C to 36°C and one can partake in adventures like surfing, swimming, canoeing, snorkeling, scuba diving, water skiing, kayaking and so on.\n \n After the summer months, monsoon rains between June and August, make the place even greener. The peak season in Lakshadweep is from December to February.";
      case "MUNNAR KERALA" : return "This is the heart of Kerala. This hill station is famous for green environment, rugged peaks, endless plantations, unique wildlife sanctuaries and national parks. This is also the land of Kurunji flower, the one that blooms once in 12 years. Explore Munnar which is one of the famous places to visit in India.";
      case "BELUR TEMPLE": return "Belur, a taluk headquarters in Hassan district, situated on the banks of Yagachi River at a distance of 38 Kms. from Hassan was known as Velapuri, Velur, Belapur and Dakshina Varanasi in earlier times. It was once the capital of the Hoysalas before Dwarasamudra (Halebidu) became their capital.\n \nThe Channakeshava temple is dedicated to Lord Channakeshava , meaning handsome Vishnu is the main temple of Belur. The temple is one of the finest examples of Hoysala architecture; it was built by king Vishnuvardhana in commemoration of his victory over the Cholas at Talakad in 1117 A.D. The Channakeshava temple is one of the earliest star shaped temples of the Hoysalas. The idol of Channakeshava is about 3.7 metres high and the madanika figures supporting the caves of the outer walls of the temples are excellent works of art. The Prabhavali of Channakeshava idol consists of the artistically carved Dashavatharas of Vishnu.";
      case "SAMOSA": return "A samosa can differ in shape, size, and fillings based on the region but have the same basics no matter where they are found. Samosas are basically Indian calzones. They feature a crusty exterior that is deep-fried and is filled with a variety of vegetables such as potatoes, meats, or lentils that are heavily seasoned. Samosas are served alongside mint sauce, tamarind sauce, and spicy green sauce, which compliments the samosa well. Samosas are found in India and can be found in the Middle East.";
      case "MASALA CHAI": return "It's is not food, but rather a type of tea. One of the most traditional and most classic staples of Indian foods is Masala Chai. Masala Chai differs from the traditional British or American teas that most people are accustomed to. Masala Chai starts with fresh tea leaves derived from the tea plantations of Assam or West Bengal. The black tea leaves are then steeped in hot water and mixed with shredded ginger and cardamom seeds to hint at spiciness. Following the brewing process, milk is added, and it is served hot and fresh.";
      case "DHOKLA": return "Coming from the Indian state of Gujarat is the Dhokla. Dhoklas are made with fermented batter derived from split chickpeas and rice and can be eaten for virtually any course. Dhoklas are eaten in India as side dishes, for breakfast, as the main course, and even as a snack at events such as parties and weddings. Dhoklas are best served with green mint sauce and a sweet tamarind sauce and are usually yellow in color. Dhoklas have many variations to them. They can be prepared with various ingredients with different ratios of chickpeas.";
      case "VADA PAV": return "The Vada refers to a deep-fried potato fritter placed between two pieces of bread, the pav. Due to this dish's resemblance to a sandwich or a burger is commonly known as the Bombay burger because of its origin in the North Indian city of Mumbai, formerly known as Bombay. The Vada Pav is served with chutneys such as green sauces and tamarind sauces. Alongside the Pav is also a green chili.";
      case "CHANA MASALA": return "Chana Masala must be added to every Indian spread to give it a magical and unforgettable taste. This meal originated from Punjab in the North of India and consists of mixed spice chickpeas. The Chana Masala contains amchoor powder, coriander, and several powdered and fresh chilies. Moreover, this dish is high in fiber and protein, thanks to its chickpeas. The latter are cooked in a spicy and fragrant tomato sauce, to which is added garam masala, a unique blend of spices, giving the Chana Masala its unique taste.";
      case "THALI": return "It is a traditional Indian food served on a round plate, including rice, flatbreads, yogurt, curry, vegetables and desserts.";
      case "BIRYANI": return "It refers to fried rice cooked with several seasonings, especially saffron, and the marinated meat like chicken or mutton.";
      case "MASALA DOSA": return "Rice is a staple of south Indian cuisine and is used in most dishes, including the finger-licking masala dosa. While dosa is a generic south Indian dish, masala dosa has specific origins in coastal Karnataka. The preparation of the rice crèpe is relatively simple: rice and lentils are soaked in water for five to six hours to prepare the batter, which is then cooked on a skillet. The types of filling in masala dosa varies, but is usually a potato and onion curry dipped in chutney.";
      case "INDIAN CHAATS": return "Chaats (savoury snacks) are a mainstay of Indian street food. Popular snacks include kachori, pani puri, bhel puri and masala puri, with a base of puffed rice and peas, vegetables and spices. Chaats originated in north India, and gradually spread to every corner of the country. It’s no exaggeration to say that once you’ve tried chaats, you’ll keep going back for more.";
      case "GULAB JAMUN": return "This popular Indian dessert is based on two flavors – gulab (which means rose) and jamun (which refers to purple jamun berries, similar to blueberries).\n \nUsing milk solids and flour, the dessert consists of small doughy balls soaked in rose water and green cardamom.\n \nThink of it like Indian doughnuts dipped in mouth-watering syrup! (But, sorry, ordinary doughnuts won’t ever taste as good again after you’ve tried gulab jamuns.)";
      case "KUMARAKOM": return "The village of Kumarakom is a cluster of little islands on the Vembanad Lake, and is part of the Kuttanad region. The bird sanctuary here, which is spread across 14 acres is a favourite haunt of migratory birds and an ornithologist's paradise. Egrets, Darters, Herons, Teals, Waterfowls, Cuckoo, Wild Duck and migratory birds like the Siberian Stork visit here in flocks and fascinate all visitors.\n \n ";
      case "LEH": return "Few places in India are at once so traveler friendly and enchanting as mountain-framed Leh. Dotted with stupas and whitewashed houses, the Old Town is dominated by a dagger of steep rocky ridge topped by an imposing Tibetan-style palace and fort. Beneath, the bustling bazaar area is draped in a thick veneer of tour agencies, souvenir shops and tandoori-pizza restaurants, but a web of lanes quickly fans out into a green suburban patchwork of irrigated barley fields.\n \n Here, gushing streams and narrow footpaths link traditionally styled Ladakhi garden homes that double as charming, inexpensive guesthouses. Leh’s a place that’s all too easy to fall in love with – but take things very easy on arrival as the altitude requires a few days' acclimatization before you can safely start enjoying the area's gamut of adventure activities.";
      case "PACHMARHI": return "Etched on Satpura range, the hills of Pachmarhi are mystically related to lord Shiva by means of legends passed down over generations. Located at an altitude of 1,067 meters, Pachmarhi is different from anything you’ll experience in Madhya Pradesh and is a perfect destination for a weekend getaway. Located at one of the hilly region in the state, the place is pretty popular with nature lovers, spiritual seekers, and sportspersons. Captain James Forsyth, a British Army Officer, came here in 1857 and the town interested him much. Caves-shrines of Shiva, dense forests, and steep-sided valleys located here offer a rich experience to the escapist travellers. Pack your bags to enjoy the feeling of calm that the magnificent nature gives. While exploring the extraordinary diversity of Madhya Pradesh, don’t miss out on this majestic landscape.";
      case "SIMLIPAL": return "Similipal Tiger Reserve which spreads over 2750 Sq.Kms is a part of Central Indian Landscape. Not only a Tiger Reserve, Similipal is also a National Park, Wildlife Sanctuary, Biosphere Reserve and also a part of Mayurbhanj Elephant Reserve. Similipal derives its name from the abundance of Semul or Red Silk Cotton trees that bloom vividly in its forest. The vast stretches of forest of Similipal is a unique composition of deciduous, semi-ever green, high level Sal, grass land & savannahs. \n\nThere are many species of rare, endangered, threatened and vulnerable plants and animals";
      case "KOTAGIRI": return "Set amidst the serenity of the Nilgiri Hills, Kotagiri is a small hill resort surrounded by lush green tea estates. Kotagiri, situated 1793 m above sea level has a climatic advantage, as it is shielded by the Doddabetta ranges from the onslaught of the monsoons. Retaining the essence of hill magic and charm, the resort offers year-round clement weather and sylvan charm. It is the third largest and the oldest hill town in the Nilgiris. Like most hill stations in India, the thick colonial era can be sensed in these mountains. It has a Kota temple in the middle of the town, even though the Kota tribes have long moved out of this place";
      case "NALBARI": return "This entire district is in the plains of the Brahmaputra Valley of the exotically beautiful Assam. The tributaries of the Brahmaputra, Nona, Buradia, Pagaldia, Borolia and Tihu which originate from the foothills of the Himalayan range, contribute enormously towards the agrarian economy of the district. 'Nalbari' means a place of reeds. The name was founded by the British Railway Engineers around in A.D. 1890-91. The former name of this place was Satra, Govindapur and Khata. The history of Nalbari is connected with King Jarashandha and Lord Krishna. Nalbari is also known as 'Navadivipa' of Assam. The place is well known for its rustic charm and ancient temples making it enthralling for tourists especially during religious festivals.";
      case "MAJULI": return "Majuli is a picturesque, lush green and pollution-free river island in the mighty River Brahmaputra. It is the world's largest river island and it attracts tourists from all over the world. Majuli is also a strong contender for a place in UNESCO's World Heritage Sites. Mostly inhabited by Tribals, the culture of Majuli is unique. It is also called the cultural capital of Assam. The festivals celebrated here are all full of joy and vibrance with a lot of music and dance. The main festival in the town of Majuli is called Raas and seeing it is a fascinating experience.";
      case "SIBSAGAR": return "Sibsagar is a historically important part of Assam, lying East of Jorhat. Being the capital of the former rulers, the Ahoms, it has had a major impact in the culture. It is a town of decorated monuments and temples.Sibsagar gets the attention of history enthusiasts who've looked to understand the East of India better. It has also played a significant role in Indian history and therefore is an important destination for historical tourism. A few architectural marvels at Sibsagar are the Talatal Ghar, Rang Ghar and the Rangpur Palace.";
      case "KORAPUT": return "Koraput District located in the backdrop of green valley’s contemplating immaculate freshness, was established on 1st April, 1936. Decorated by forests, waterfalls, terraced valleys and darting springs, the District draws the nature loving people. The District is bounded by Rayagada in the east, Bastar District of Chhatisgarh in the west and Malkangiri District in the south. As far as the history of the District is concerned, the region of Koraput existed far back in the 3rd century BC when it belonged to the valiant and dreaded Atavika people. ";
      case "UDAIPUR": return "Popularly known as the City of Lakes, serene Udaipur is the crowning jewel of royal Rajasthan. With shimmering lakes visible from almost every rooftop, fairytale palaces, sprawling havelis, revered temples and narrow lanes weaving through colourful markets as ancient as the city's history, Udaipur's charm is unmatched.Founded by Maharaja Udai Singh II in 1559, the city served as the capital of the kingdom of Mewar after Mughal emperor Akbar besieged its earlier power-centre Chittorgarh. Udaipur is also referred to as the Venice of the East, a title it has earned for being dotted with numerous lakes (seven to be precise)! Nestled in the mighty Aravalli range, surrounded by dense forests and craggy hills, and magical sunrises and sunsets turning its lakes into pools of gold, Udaipur is one of the most picturesque destinations in the country. Colonel James Tod of the East India Company, who was also a scholar, aptly described the city as “the most romantic place in the Indian sub continent”.";
      case "": return "";
    }
    return "Description not yet updated";
  }
}
